export const PAGE_PATHS = {
  admins: "/admins",
  books: "/books",
  bookCategories: "/books-categories",
  dashboard: "/dashboard",
  groups: "/groups",
  groupSets: "/groups/sets",
  notFound: "*",
  notifications: "/notifications",
  profile: "/profile",
  root: "/",
  siginIn: "/siginin",
  trending: "/trending",
  users: "/users",
};
